### ISSUE TITLE
Crash on release after cropping screen

### ISSUE THREAD

**Issue by abhay-s-rawat** [ishaquehassan/document_scanner_flutter#16]
Everything working fine in debug mode but in release mode when I do crop and hit the button to proceed it crashes and app restarts.
Following are the logs when it happens.

E/AndroidRuntime(16392): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(16392): Process: com.example.myappnullsafety, PID: 16392
E/AndroidRuntime(16392): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(16392):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(16392):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(16392):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(16392):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(16392):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(16392):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(16392):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(16392):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(16392): Caused by: java.lang.UnsatisfiedLinkError: No implementation found for android.graphics.Bitmap com.scanlibrary.ScanActivity.f(android.graphics.Bitmap, float, float, float, float, float, float, float, float) (tried Java_com_scanlibrary_ScanActivity_f and Java_com_scanlibrary_ScanActivity_f__Landroid_graphics_Bitmap_2FFFFFFFF)
E/AndroidRuntime(16392):        at com.scanlibrary.ScanActivity.f(Native Method)
E/AndroidRuntime(16392):        at com.scanlibrary.O.e(:1)
E/AndroidRuntime(16392):        at com.scanlibrary.M.doInBackground(:1)
E/AndroidRuntime(16392):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(16392):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(16392):        ... 4 more
W/FlutterActivityAndFragmentDelegate(17670): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.

**Comment by AviralDhingra** [comment]
@abhay-s-rawat I am facing the same issue. Did you find any solution?

**Comment by wishtree-skaranje** [comment]
I am also facing the same issue

`java.lang.UnsatisfiedLinkError: No implementation found for android.graphics.Bitmap com.scanlibrary.ScanActivity.f(android.graphics.Bitmap, float, float, float, float, float, float, float, float) (tried Java_com_scanlibrary_ScanActivity_f and Java_com_scanlibrary_ScanActivity_f__Landroid_graphics_Bitmap_2FFFFFFFF)
        at com.scanlibrary.ScanActivity.f(Native Method)
        at com.scanlibrary.O.e(:1)`

**Comment by belwinbrk** [comment]
any solution
