### ISSUE TITLE
Crashes when image is selected from gallery (For image scan)

### ISSUE THREAD

**Issue by ManjunathVMK** [ishaquehassan/document_scanner_flutter#27]
java.lang.RuntimeException: Canvas: trying to draw too large(143952004bytes) bitmap.
E/AndroidRuntime(12150): 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
E/AndroidRuntime(12150): 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
E/AndroidRuntime(12150): 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
E/AndroidRuntime(12150): 	at android.widget.ImageView.onDraw(ImageView.java:1434)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21440)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20317)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20308)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21443)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20317)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20308)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20308)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20308)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20308)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21172)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
E/AndroidRuntime(12150): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
E/AndroidRuntime(12150): 	at android.view.View.draw(View.java:21443)
E/AndroidRuntime(12150): 	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
E/AndroidRuntime(12150): 	at android.view.View.updateDisplayListIfDirty(View.java:20317)
E/AndroidRuntime(12150): 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
E/AndroidRuntime(12150): 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
E/AndroidRuntime(12150): 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
E/AndroidRuntime(12150): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3608)
E/AndroidRuntime(12150): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3416)
E/AndroidRuntime(12150): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2753)
E/AndroidRuntime(12150): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1719)
E/AndroidRuntime(12150): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7602)
E/AndroidRuntime(12150): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
E/AndroidRuntime(12150): 	at android.view.Choreographer.doCallbacks(Choreographer.java:852)
E/AndroidRuntime(12150): 	at android.view.Choreographer.doFrame(Choreographer.java:787)
E/AndroidRuntime(12150): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
E/AndroidRuntime(12150): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(12150): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(12150): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(12150): 	at android.app.ActivityThread.main(ActivityThread.java:7403)
E/AndroidRuntime(12150): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12150): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(12150): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by 3rsin3rgul-Corplife** [comment]
+1

**Comment by anthonycuervo23** [comment]
having the same issue when I pick image from gallery and sometimes with an image from camera, is there any solution for this? it happens only with some android devices

**Comment by bsbilal** [comment]
same

**Comment by SantiagoBarbosaNieto** [comment]
Same, with android device: POCO X4 Pro 5G running with android 11

**Comment by gerica** [comment]
It seems to me that I have to reduce the image, but I don't know how to do it.
